# Generated by Django 5.0.4 on 2024-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="name",
        ),
        migrations.AddField(
            model_name="item",
            name="cpf",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="data_nascimento",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AddField(
            model_name="item",
            name="nome",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
