# Generated by Django 5.0.4 on 2024-07-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bdApp", "0002_remove_item_name_item_cpf_item_data_nascimento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
    ]
