# Generated by Django 5.0.4 on 2024-07-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bdApp", "0003_remove_item_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="Usuario",
        ),
    ]
